// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYfraQRfIN6VPiZlBOIQiy0c-hexPpIV4',
    appId: '1:1071242214632:web:1d91be0a0e785eb54f5d5d',
    messagingSenderId: '1071242214632',
    projectId: 'projectv1-48c52',
    authDomain: 'projectv1-48c52.firebaseapp.com',
    storageBucket: 'projectv1-48c52.firebasestorage.app',
    measurementId: 'G-BP2Z21MK6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljQ0-PD1HKLPW9du6nPefG15D2ztmLBE',
    appId: '1:1071242214632:android:9b6764949f68954c4f5d5d',
    messagingSenderId: '1071242214632',
    projectId: 'projectv1-48c52',
    storageBucket: 'projectv1-48c52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhaeUC--U064ydecuPAfrxPWbXUcswoY',
    appId: '1:1071242214632:ios:5d79ebe4fc3762d94f5d5d',
    messagingSenderId: '1071242214632',
    projectId: 'projectv1-48c52',
    storageBucket: 'projectv1-48c52.firebasestorage.app',
    iosBundleId: 'com.example.projectV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuhaeUC--U064ydecuPAfrxPWbXUcswoY',
    appId: '1:1071242214632:ios:5d79ebe4fc3762d94f5d5d',
    messagingSenderId: '1071242214632',
    projectId: 'projectv1-48c52',
    storageBucket: 'projectv1-48c52.firebasestorage.app',
    iosBundleId: 'com.example.projectV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYfraQRfIN6VPiZlBOIQiy0c-hexPpIV4',
    appId: '1:1071242214632:web:80bb1ef3b43577be4f5d5d',
    messagingSenderId: '1071242214632',
    projectId: 'projectv1-48c52',
    authDomain: 'projectv1-48c52.firebaseapp.com',
    storageBucket: 'projectv1-48c52.firebasestorage.app',
    measurementId: 'G-NEQJK8Q6T1',
  );
}
